name: deploy page

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: the node.js thing
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install deps
        run: |
         sudo apt-get install gcc
         sudo apt-get install gfortran
         sudo apt-get install graphviz
         python3 -m pip install tomli==2.0.1
         python3 -m pip install toposort==1.7
         python3 -m pip install ford==7.0.8

      - name: build
        run: |
          ls -a ${{github.workspace }} 
          cd docs && ford ford.md 
        
      - name: Archive artifact
        shell: sh
        if: runner.os == 'Linux'
        run: |
          ls -a ${{github.workspace }}
          ls -a ${{github.workspace}}/docs
          tar \
          --dereference --hard-dereference \
          --exclude=.git \
          --exclude=.github \
          -cvf "$RUNNER_TEMP/artifact.tar" \
          --directory=docs/public .
          ls -l ${{ runner.temp }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          if-no-files-found: error

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
