name: deploy page

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: node.js thing
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # installation
      - name: install deps
        run: |
         python3 -m pip install numpy==1.24.2
         python3 -m pip install six==1.16.0
         python3 -m pip install sphinx==5.3.0
         python3 -m pip install sphinx-rtd-theme==1.1.1
         python3 -m pip install sphinx-sitemap==2.2.1
         python3 -m pip install breathe==4.34.0
         python3 -m pip install sphinx-fortran==1.1.1


      - name: build
        run: ls -a ${{github.workspace }} && cd docs && make html
        #run: sphinx-build -b html docs public
      #- run: make html

      # page
      - name: deploy to page
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
